# generated by datamodel-codegen:
#   filename:  openapi.yaml

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional


class FinishReason(Enum):
    success = 'success'
    error = 'error'
    canceled = 'canceled'


@dataclass
class AgentOperation:
    name: str
    description: str
    input_schema: Optional[Dict[str, Any]] = None
    output_schema: Optional[Dict[str, Any]] = None


@dataclass
class AgentDescriptor:
    name: str
    purpose: str
    endpoints: List[str]
    operations: List[AgentOperation]
    tools: Optional[List[str]] = field(default_factory=list)


@dataclass
class Event:
    id: int
    run_id: str
    agent: str
    type: str
    depth: Optional[int] = 0
    timestamp: Optional[str] = None


@dataclass
class Request:
    request_id: str
    logging_level: Optional[str] = None
    request_metadata: Optional[Dict[str, Any]] = field(default_factory=dict)


@dataclass
class ChatRequest:
    request_id: str
    input: str
    logging_level: Optional[str] = None
    request_metadata: Optional[Dict[str, Any]] = field(default_factory=dict)
@dataclass
class ConfigureRequest:
    request_id: str
    args: Dict[str, Any]
    logging_level: Optional[str] = None
    request_metadata: Optional[Dict[str, Any]] = field(default_factory=dict)
@dataclass
class CancelRequest:
    request_id: str
    logging_level: Optional[str] = None
    request_metadata: Optional[Dict[str, Any]] = field(default_factory=dict)
@dataclass
class ResumeWithInput:
    request_id: str
    request_keys: Dict[str, Any]
    logging_level: Optional[str] = None
    request_metadata: Optional[Dict[str, Any]] = field(default_factory=dict)
@dataclass
class RequestStarted:
    id: int
    run_id: str
    agent: str
    type: str
    request_id: str
    depth: Optional[int] = 0
    timestamp: Optional[str] = None
@dataclass
class WaitForInput:
    id: int
    run_id: str
    agent: str
    type: str
    request_keys: Dict[str, str]
    depth: Optional[int] = 0
    timestamp: Optional[str] = None
@dataclass
class TextOutput:
    id: int
    run_id: str
    agent: str
    type: str
    content: str
    depth: Optional[int] = 0
    timestamp: Optional[str] = None
@dataclass
class ToolCall:
    id: int
    run_id: str
    agent: str
    type: str
    function_name: str
    args: Dict[str, Any]
    depth: Optional[int] = 0
    timestamp: Optional[str] = None
@dataclass
class ToolResult:
    id: int
    run_id: str
    agent: str
    type: str
    function_name: str
    text_result: str
    depth: Optional[int] = 0
    timestamp: Optional[str] = None
@dataclass
class ArtifactGenerated:
    id: int
    run_id: str
    agent: str
    type: str
    name: str
    artifact_id: str
    url: str
    mime_type: str
    depth: Optional[int] = 0
    timestamp: Optional[str] = None
@dataclass
class OperationComplete:
    id: int
    run_id: str
    agent: str
    type: str
    finish_reason: FinishReason
    depth: Optional[int] = 0
    timestamp: Optional[str] = None
